### ISSUE TITLE
Needs more gifs of cats!

### ISSUE THREAD

**Issue by gedankenstuecke** [sourabhlal/github_flow_demo#11] opened 2018-09-10 12:16 UTC
This repo would profit from having cute cat gifs! 

![cat gif](https://media.tenor.co/images/5998dc6b4576b29ba1d61a084f3d79d0/tenor.gif)

**Comment by gedankenstuecke** [comment] 2018-09-10 12:17
Happens that this was submitted independently from #9!

**Comment by annakrystalli** [comment] 2018-09-10 12:17
Duplicate of #9  😜

**Closed** 2018-09-10 12:27 UTC
